<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>488</string>
	</array>
	<key>name</key>
	<string>CSC488 Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(begin)</string>
			<key>name</key>
			<string>keyword.other.begin.488</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(end)</string>
			<key>name</key>
			<string>keyword.other.end.488</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(do|while|when|return|skip|yields|loop|exit|function|procedure)</string>
			<key>name</key>
			<string>keyword.control.488</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(if|else|then)</string>
			<key>name</key>
			<string>keyword.operator.488</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(get|put)</string>
			<key>name</key>
			<string>support.function.488</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(integer|boolean)</string>
			<key>name</key>
			<string>storage.type.488</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(true)</string>
			<key>name</key>
			<string>constant.language.true.488</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(false)</string>
			<key>name</key>
			<string>constant.language.false.488</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.js</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.js</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.quoted.double.488</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(.+)\s*(\&lt;\=)\s*(.+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.488</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>support.other.488</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>variable.complex.488</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.other.488</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(%).*$\n?</string>
			<key>name</key>
			<string>comment.line.percentage.488</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.488</string>
	<key>uuid</key>
	<string>5f42d0f2-1948-4073-8636-cfa4584d451e</string>
</dict>
</plist>
